(function(w){
var enc=new TextEncoder(),dec=new TextDecoder();
function deriveKey(pw,salt){return crypto.subtle.importKey("raw",enc.encode(pw),{name:"PBKDF2"},false,["deriveKey"]).then(function(mat){return crypto.subtle.deriveKey({name:"PBKDF2",salt:salt,iterations:310000,hash:"SHA-256"},mat,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);});}
function writeU32(b,o,v){b[o]=(v>>>24)&255;b[o+1]=(v>>>16)&255;b[o+2]=(v>>>8)&255;b[o+3]=v&255;}
function readU32(b,o){return((b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3])>>>0;}
function encryptFileToSafe(file,password,onProgress){if(!crypto||!crypto.subtle)return Promise.reject(new Error("مرورگر شما از Web Crypto API پشتیبانی نمی‌کند."));function prog(p,t){if(typeof onProgress==="function")onProgress(p,t);}prog(5,"در حال خواندن فایل...");return file.arrayBuffer().then(function(plain){prog(20,"در حال آماده‌سازی کلید...");var salt=new Uint8Array(16);crypto.getRandomValues(salt);return deriveKey(password,salt).then(function(key){prog(35,"در حال ساخت هدر SAFE...");var headerIv=new Uint8Array(12);var dataIv=new Uint8Array(12);crypto.getRandomValues(headerIv);crypto.getRandomValues(dataIv);var meta={v:1,name:file.name,size:file.size,type:file.type||"application/octet-stream",createdAt:new Date().toISOString()};var headerPlain=enc.encode(JSON.stringify(meta));return crypto.subtle.encrypt({name:"AES-GCM",iv:headerIv},key,headerPlain).then(function(hcAb){var headerCipher=new Uint8Array(hcAb);prog(60,"در حال رمزنگاری محتوای فایل...");return crypto.subtle.encrypt({name:"AES-GCM",iv:dataIv},key,plain).then(function(dcAb){var dataCipher=new Uint8Array(dcAb);prog(85,"در حال ساخت فایل خروجی SAFE...");var magic=enc.encode("SAFE");var saltLen=salt.length,headerIvLen=headerIv.length,dataIvLen=dataIv.length,headerCipherLen=headerCipher.length;var headerLen=magic.length+1+1+1+1+1+4+saltLen+headerIvLen+dataIvLen+headerCipherLen;var out=new Uint8Array(headerLen+dataCipher.length);var off=0;out.set(magic,off);off+=magic.length;out[off++]=1;out[off++]=0;out[off++]=saltLen;out[off++]=headerIvLen;out[off++]=dataIvLen;writeU32(out,off,headerCipherLen);off+=4;out.set(salt,off);off+=saltLen;out.set(headerIv,off);off+=headerIvLen;out.set(dataIv,off);off+=dataIvLen;out.set(headerCipher,off);off+=headerCipherLen;out.set(dataCipher,off);prog(100,"رمزنگاری با موفقیت انجام شد.");return{buffer:out.buffer,metadata:meta};});});});});}
function decryptSafeFile(file,password,onProgress){if(!crypto||!crypto.subtle)return Promise.reject(new Error("مرورگر شما از Web Crypto API پشتیبانی نمی‌کند."));function prog(p,t){if(typeof onProgress==="function")onProgress(p,t);}prog(5,"در حال خواندن فایل SAFE...");return file.arrayBuffer().then(function(ab){var buf=new Uint8Array(ab);var off=0;var magic=dec.decode(buf.subarray(0,4));if(magic!=="SAFE")throw new Error("این فایل با فرمت SAFE سازگار نیست.");off+=4;var version=buf[off++];var flags=buf[off++];if(version!==1)throw new Error("نسخه فایل SAFE پشتیبانی نمی‌شود.");var saltLen=buf[off++];var headerIvLen=buf[off++];var dataIvLen=buf[off++];var headerCipherLen=readU32(buf,off);off+=4;var salt=buf.subarray(off,off+saltLen);off+=saltLen;var headerIv=buf.subarray(off,off+headerIvLen);off+=headerIvLen;var dataIv=buf.subarray(off,off+dataIvLen);off+=dataIvLen;var headerCipher=buf.subarray(off,off+headerCipherLen);off+=headerCipherLen;var dataCipher=buf.subarray(off);prog(25,"در حال مشتق‌سازی کلید از رمز عبور...");return deriveKey(password,salt).then(function(key){prog(45,"در حال رمزگشایی اطلاعات هدر...");return crypto.subtle.decrypt({name:"AES-GCM",iv:headerIv},key,headerCipher).then(function(hpAb){var headerPlain=new Uint8Array(hpAb);var meta;try{meta=JSON.parse(dec.decode(headerPlain));}catch(e){throw new Error("رمز عبور نادرست است یا هدر فایل آسیب دیده است.");}prog(75,"در حال رمزگشایی محتوای فایل...");return crypto.subtle.decrypt({name:"AES-GCM",iv:dataIv},key,dataCipher).then(function(dpAb){prog(100,"رمزگشایی با موفقیت انجام شد.");return{buffer:dpAb,metadata:meta};});});});});}
w.SAFE_CRYPTO={encryptFileToSafe:encryptFileToSafe,decryptSafeFile:decryptSafeFile};
})(window);
